### ISSUE TITLE
Need more details about test at README.md

### ISSUE THREAD

**Issue by Philmist** [rpgtkoolmv/corescript#1]
README.md says
````
To test, place MV’s project in game/ and type
npm test
````
I copy all files from project folder (contains `Game.rpgproject`) to `./game/` directory.
But error occurs (`TypeError undefined is not a function`(TestPlay in Editor) or `TypeError WebAudio.Initialize is not a function`(Open Index.html at firefox) ).

Is this method correct or something wrong?

**Comment by ghost** [comment]
What version of RPG Maker you generated by? 
To find your project's version, open Game.rpgproject by Text Editor.

If you use Plugins, turn off them all. it may conflict.
But, we concern about Plugins compatibility, please report conflicted plugin if you can.

**Comment by Philmist** [comment]
`RPGMV 1.3.1` is written in `Game.rpgprojet`.
I didn't know this is old version of RPG Maker MV.
I'll try to update MV, and report it later.

**Comment by Philmist** [comment]
I update RPG Maker MV from 1.3.1 to 1.3.4.

Create blank project (New project) and copy files to repository direcotory,
It works!

Sorry for my mistake.
