### ISSUE TITLE
makeVideoPlayableInline is not defined

### ISSUE THREAD

**Issue by Michael-K-GH** [rpgtkoolmv/corescript#113]
After replacing the scripts in my project folder with the ones from here, I get this error appear when trying to run my project.  Commenting out the call to makeVideoPlayableInline() in the scripts fixes this issue.

**RMMV**: 1.4.0
**corescript**: 1.2c
**OS**: Windows 10 x64 (Creators Update)

**Comment by krmbn0576** [comment]
I think that you may have failed to replace the scripts.
Please use the bundled *Debug_HealthCheck.js* plugin.

**Comment by Michael-K-GH** [comment]
I copied the scripts from /dist/ in to my project's /js/ folder.  Am I missing something?

**Comment by krmbn0576** [comment]
Furthermore, copy *index.html* and *GameFont.css* from /template/.

Hmm, it's hard to realize.
We'll write how to copy on readme.md. 😉

**Comment by Michael-K-GH** [comment]
I also had to copy the /libs/ folder over to my projects /js/ folder (iphone-inline-video.browser.js was missing from my project).  After that, it seems to work just fine.  Gonna go ahead and close this issue now, thanks.
