### ISSUE TITLE
Use original source and build  script(PR pending until this issue is closed)

### ISSUE THREAD

**Issue by ghost** [rpgtkoolmv/corescript#12]
Original Author requested to use original source and build script(Grunt).

We have to work based on the original source, so any PR will be pending.
Sorry for inconvenience.

**Comment by niokasgami** [comment]
what do you mean by 'use original source and build script'? 
do you mean that now it's impossible to edit the core file like you guys want? even if it's improving the perfomance a lots?

**Comment by ghost** [comment]
We mean to start with orignal project layout and source.
We started by Compiled source, so original author requested to start with original layout and source.

**Comment by ghost** [comment]
and Original Author accepted to rewrite original buildscripts to npm scripts, so we do it just now.

**Comment by hajimehoshi** [comment]
So, we can close this issue and continue to send PRs?

**Comment by ghost** [comment]
Yes! I'll close this issue.
