### ISSUE TITLE
New Problems With Pixi and Pixi-Tilemap

### ISSUE THREAD

**Issue by krmbn0576** [rpgtkoolmv/corescript#124]
@ivanpopelyshev Congratulations for RPG Maker Version 1.5.1 and Pixi 4.5.4!
But we founded 2 problems with pixi.js and pixi-tilemap.js. 😢 

1. Tilemap isn't displayed for a moment after NewGame (only parallax is displayed)
1. Type error for android deployment (https://forums.rpgmakerweb.com/index.php?threads/type-error-for-android-deployment-in-rmmv-1-5-0.80359/)

Could you fix them?

**Comment by ivanpopelyshev** [comment]
Tilemap is my problem, that's why #112 is still not merged :)

Fonts aren't mine , I 've made a simple fix somewhere in rmmv core, but im not sure. Fonts issue  actually came from this repo (atsamaru)

**Comment by krmbn0576** [comment]
Ohh I finally understood!
2. is the same problem as #118 ...
Thanks! 😇

**Comment by ivanpopelyshev** [comment]
Tried to fix it today, rewrote some parts -> same problem.
