### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by oott123** [rpgtkoolmv/corescript#132]
On Chrome for Android 61, when user click anywhere inside screen, there will be a warning displayed:

```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
TouchInput._onTouchStart @ rpg_core.js:3320
```

Meanwhile, the click will be trigger 2 times, you will here 2 times SE and your switch will changed twice.

According to <https://www.chromestatus.com/features/5093566007214080>, ontouchstart listener become passive by default after Chrome 56, which means you cannot preventDefault inside it.

**Comment by krmbn0576** [comment]
We supported passive event in #71 
Isn't it enough?
