### ISSUE TITLE
Background preloading

### ISSUE THREAD

**Issue by ghost** [rpgtkoolmv/corescript#16]
see https://github.com/rpgtkoolmv/corescript/pull/13

**Comment by ghost** [comment]
Some preload is missing now.

**Comment by krmbn0576** [comment]
background preload for `Game_Interpreter` is now implemented!
See #42

**Comment by Philmist** [comment]
This issue should be closed because of merged PR.
another issue?

**Comment by ghost** [comment]
nope, thanks
