### ISSUE TITLE
clean project !

### ISSUE THREAD

**Issue by jonlepage** [rpgtkoolmv/corescript#165]
need to fix
possibility to name project with point (.)
it is not urgent, but on the side of the america and europa, the developers tends to classify their files and folders version with points to allow the window to understand the indexation.
it a very easy fix.
![sans titre-1](https://user-images.githubusercontent.com/24865815/41081521-322b39a8-69f9-11e8-9731-908073d5ba8f.png)
I am forced to change everything manually every time.
i name with _ , after siwtch to . , waste of time
thanks

I also have another complaint.
it would be nice to include a destroy button in the editor.
To delete all content for work with a pure js editor.
a big problem is that also if we put to 0 "null" 'delete' some functionality in the editor, the game crash.
I find it not good for a open software.

we need manually delete in js and in the editor content.
but..
ALSO it not able to get a clear projet without error.
we need hack js to get not error if we start with clear project.

this it unacceptable for a software 150$.

![sans-titre-1](https://user-images.githubusercontent.com/24865815/41081531-35e28812-69f9-11e8-9a05-bd0ccd88f3b8.jpg)

i complaint because moderator tell us they lisen dev, but if we look here..
https://forums.rpgmakerweb.com/index.php?forums/approved-features.169/

only moderator approved and nothing about dev approved since a many year.
please jap check this 
https://forums.rpgmakerweb.com/index.php?forums/editor-suggestions-and-improvement.168/

**Comment by krmbn0576** [comment]
Sorry, MV editor is **NOT** OSS.
Only MV JavaScript is OSS.

Unfortunately, we also have no way to communicate your claims to editor's developers team. 😢
