### ISSUE TITLE
BattleTest and EventTest can't start

### ISSUE THREAD

**Issue by rev2nym** [rpgtkoolmv/corescript#176]
BattleTest and EventTest can't be started by RPGM MV editor ver 1.6.1.

**Comment by krmbn0576** [comment]
Thanks!
Now corescript is based on RMMV 1.4.1, so `Utils.isOptionValid()` is still old.
We'll merge 1.6.1 soon later!

**Comment by rev2nym** [comment]
Thank you.

Please keep in mind that official 1.6.1 method is a bit inappropriate.
- It returns `0/1`. Expected return value is `bool` type.
- It is very hard to read because the line is so long.
