### ISSUE TITLE
Make it clear whether to format the code

### ISSUE THREAD

**Issue by krmbn0576** [rpgtkoolmv/corescript#24]
@liply You formatted the code once, but you remanded it. (d293b78)
However, your PR contains just a few lines just to format the code.
It is hard to see and review.

So we should choose whether to format the code before sending the PR or to give up formatting and remove the formatting of the code from the PR.
Either way, the description about the formatting of the code from PR will disappear.

**Comment by ghost** [comment]
Sorry, I just copy & paste from my branch, and It contains formatted code.
I'll try remove formatted only code.

**Comment by ghost** [comment]
maybe done. please tell me if such code is found.
