### ISSUE TITLE
Versioning Scheme in Utils.RPGMAKER_VERSION

### ISSUE THREAD

**Issue by ghost** [rpgtkoolmv/corescript#25]
Some says It's not preferable to edit Utils.RPGMAKER_VERSION.

Suggestion is:
Make Utils.RPGMAKER_ENGINE parameter, and edit it.

I think this suggestion is good.
Like this:
Utils.RPGMAKER_ENGINE = 'dev-1.1';

I want to follow this suggestion, Is there any ideas?

**Comment by niokasgami** [comment]
the problem is that this version is what permit the game to know wich version you use.
AKA if you create a new game and open the game file with notepad or a IDE you will notice it's states the Number of the versions

**Comment by ghost** [comment]
First, we try to modify Utils.RPGMAKER_VERSION.
Some says It's not good for compatibility.

So we had better add RPGMAKER_ENGINE. Vanilla doesn't have such parameter, so plugin creator can recognize what version the creator uses(community version or not)

**Comment by krmbn0576** [comment]
My second thoughts, we may modify `Utils.RPGMAKER_VERSION` only on RC released,
because dev-release will not be tested by so many people.

**Comment by ghost** [comment]
The version must have high compatibility to vanilla, so It's not good to modify `Utils.PRGMAKER_VERSION`.
so adding RPGMAKER_ENGINE is more preferable.

**Comment by krmbn0576** [comment]
Oh, I understood.
...???
So, we'll assign `Utils.PRGMAKER_VERSION = '1.3.4'` forever???
Please write an example of how `Utils.PRGMAKER_VERSION` and `RPGMAKER_ENGINE` change.

**Comment by ghost** [comment]
ex.
When RM reaches 1.3.5

```
Utils.RPGMAKER_VERSION = '1.3.5';
Utils.RPGMAKER_ENGINE = '1.1-dev';
```

Utils.RPGMAKER_VERSION follows compatible RM's version.

**Comment by krmbn0576** [comment]
UNDERSTOOD! agree 😇

**Comment by ghost** [comment]
OK We'll follow the rule.
