### ISSUE TITLE
Convert to pixi 4.3.4

### ISSUE THREAD

**Issue by ivanpopelyshev** [rpgtkoolmv/corescript#3]
4.3.4 version is in testing, there are few minor problems. I will make PR soon.

**Comment by Dai696** [comment]
Currently using a version of this, besides a minor issue or two, I've experienced few problems so far!

**Comment by hajimehoshi** [comment]
You mean 4.3.4 is still alpha version? What kind of problems has 4.3.4 fixed?

**Comment by ghost** [comment]
pixi is updated.
