### ISSUE TITLE
Develop a useful core plugin for creators

### ISSUE THREAD

**Issue by krmbn0576** [rpgtkoolmv/corescript#40]
In order for more people to create games conveniently and freely,
let's provide a useful core plugin in this community!

Features list:

- Several important parameters manipulate by plugin parameters - cache limit, screen resolution, FPS
- Provide useful functions for plugin creation - Nio's type conversion (See #39), liply's `wrapPrototype`, triacontane's `getParamXxxxx`, etc ...

If you want other features, please tell me!

**Comment by ghost** [comment]
The former, we'd better write them.

> Provide useful functions for plugin creation 

but This tends to be bigger. (and finally grows to WTF plugin :coffin:)
We must consider carefully about this.

IMO Like [my plugins](https://github.com/liply/mvplugins) , large plugin should use common front-end JavaScript manner.(use bundler, npm and so on)

**Comment by niokasgami** [comment]
Woa woa hold on a minute it growed in a way I didnt expected xD

The reasons I created this plugin extenders was to help peoples to short down their work or tell what their parameters exactly mean 

Its totally optionnal and shouldnt be mandatory to any other programmer

I also want to make the plugin making more friendly user to new programmer who want to begi n

So take my plugin merge offers with a pinch of salt who can be added to plugins to the peoples desire

And if some the method can be more long then you guys are free to not add those method in the actual pluginManager or to edit them

I want my offers for plugin to be a tool not something who will restrain other programmer :3

**Comment by krmbn0576** [comment]
OK, I will be cautious about providing functions. :->

**Comment by ghost** [comment]
Then, We should merge the feature if we extend PluginManager for usability.

Any proposals are welcome!!! 
Let's think about which feature is good for adding, and discuss on this thread.

**Comment by shitake2333** [comment]
If we provide a basic plugin, maybe we also need a plugin dependency mechanism? @liply 

In fact, for the plugin command, it is very similar to the command line program. mabye we can provide a toolkit like commander.js (https://github.com/tj/commander.js).

**Comment by niokasgami** [comment]
@liply  my honest suggestion would be the function I made 
"toArray"  and ToBoolean HONESTLY this the method who I think should be the most implemented in the  Plugin Manager because it's a pain to read sometime  or to split hahaha.

**Comment by ghost** [comment]
@molingyu 
> If we provide a basic plugin, maybe we also need a plugin dependency mechanism? 

Yes, we really need it.
But to solve that automatically, We need to prepare plugin registry, and It's hard to maintain.
so We'd better provide only dependency mechanism.

ex.

```
//throws error when plugin is not found.
PluginManager.checkDependency('Some_Awesome_Plugin");
```

@niokasgami 
Thank you for PR!!
I'll check it.

**Comment by krmbn0576** [comment]
I finally wrote basic plugin!!! 😇 
See #102
