### ISSUE TITLE
Review PAST changes before proceeding

### ISSUE THREAD

**Issue by krmbn0576** [rpgtkoolmv/corescript#7]
This core script has already been largely changed from the original core script.
So, we should review these changes first and foremost.

Suggestion: Re-push the original core script and send PR of past changes

**Comment by hajimehoshi** [comment]
How about creating a branch and doing that there?

**Comment by ghost** [comment]
I agree with Hoshi's suggestion.
But, I worked before decision to use github-flow, so many changes merged.

Review Process I prefer is:
* branch from https://github.com/rpgtkoolmv/corescript/commit/d2544bc95355159ce98a2b784775078964b0c0fb
* add all changes to the branch
* review it
* merge

**Comment by krmbn0576** [comment]
Sounds good ;-)

**Comment by ghost** [comment]
created!! https://github.com/rpgtkoolmv/corescript/pull/9

**Comment by ghost** [comment]
The repository is renewed by original layout. and I make PR individually.
