### ISSUE TITLE
I Propose new roadmap

### ISSUE THREAD

**Issue by iyokan-nico** [rpgtkoolmv/corescript#72]
The development of Core Script 1.1 was very good thanks to everyone.
We got a lot of feedback while developing it. Therefore we propose change of road map.

----------------
NEW roadmap
----------------
ver 1.2
Goal: Responding to problems where games can not continue
    Retry at load error
    Development of a standard plugin for options

ver 1.3
Goal: Assist in game development
    AutoSave
    Simple conflict check for plugins
    Guidelines and sample writing for plugins
    Refined bug report

ver 1.4
Goal: Accelerate speed, reduce experience time
    High-speed loading of sound source
    Progress bar on load screen
    Lightweight Save File

ver 1.5

Goal: Improve UI
    Multilingual
    Multi-touch
    Battle system touch compliance
    Touch correspondence of basic system such as equipment

**Comment by krmbn0576** [comment]
Sounds good! ;-)

**Comment by krmbn0576** [comment]
Can you add "Master Volume API" to ver1.2?
It's proposed once, but now missing.
