### ISSUE TITLE
Licesing Questions

### ISSUE THREAD

**Issue by strcter** [rpgtkoolmv/corescript#8]
こんにちは、MIT License でリリースされたcorescriptの
ライセンス上許可される事項について質問があります。

[1]
RPGツクールMVでエディットされたゲームのスクリプト部分(RTP素材などをもちろん除く)をMIT Licenseなど(Apache 2.0, BSDL, GNU GPLなどへのサブライセンスも含む)の下でゲームとして公開することは可能ですか？  
ここでいうスクリプトとは(このリポジトリで公開されている)corescript + 公開者が自ら書いたコードとライセンスによる許諾を得て使っているコードを指します。  

[2]
 ツクールシリーズ利用許諾には以下のような記述があります。  
https://tkool.jp/support/guideline  
```
素材利用の制限
お客様は上記対象製品一覧中の『ツクールシリーズ』のソフトウェアに収録されている音楽、画像、文章など、すべてのデータを、同じく上記対象製品一覧中の『ツクールシリーズ』でゲームを作成する場合においてのみ利用できます。株式会社KADOKAWA（以下「弊社」という）からの文書による承諾を得ずに、自作プログラム、および他社のゲーム作成ツールなどで作成した作品にデータを収録、利用することを一切禁止します。

素材の改変
上記対象製品一覧中の『ツクールシリーズ』のソフトウェアに収録されている音楽、画像、文章などのデータを、同じく上記対象製品一覧中の『ツクールシリーズ』でゲームを作成する場合において改変して利用することが可能です。また、特定の製品（※２）を除き、これらの収録素材を元に作成した素材について配布することも可能です。ただし、改造した素材を、単体で有償配布（販売）することは認められません。それ以外での使用を目的とする改変は禁止します。なお、一部のサンプルゲームについては、制作者との契約上、素材の２次利用が認められません（※１）。
配布可能な例）RPGツクールVXのRTPに入っているキャラクターグラフィックの髪の毛の色を変えた素材を、自分のサイトでツクール用素材として配布する。

ツクール間の素材の流用
弊社ツクールシリーズを複数組み合わせてゲーム作品を作成する場合は、使用するツクールシリーズすべてについて、各製品所定の方法で正規のユーザー登録が完了していることが条件となります。なお、一部のサンプルゲームについては、制作者との契約上、素材の２次利用が認められません（※１）。
```

もちろんRPGツクールMVの公式に販売されているエディタから作られたゲーム作品は  
ここでいうツクールシリーズに該当すると思われますが、以下の場合ツクールシリーズに該当し、  
RTPパッケージなどの配布・利用規約を満たすでしょうか？  

1. RPGツクールMVの公式エディタから出力した作品のcorescriptの部分をGitHub上のcorescriptで置き換えた場合 (テスト目的や新機能を使う目的でDevelopブランチを落としてきて置き換えることなどが想定される)  

2. corescriptを自分の用途を満たすようにフォークして、1と同様に置き換えた場合   
(この場合、rpgtkoolmv/corescriptにパッチがマージされているとは限らない)

3. rpgtkoolmv/corescriptをフォークして別のプロジェクトが立ち上がっていて、そのスクリプトを使った場合  
(大幅に改変がされ、ほとんど別物になっている場合も想定される)  

4. RPGツクールMV以外のエディタを使用し、作成されたゲーム作品だが  
corescriptでも動作するように互換性がある場合

**Comment by iyokan-nico** [comment]
This repository uses English as the main language.

1)Maybe OK.

2)Please ask KADOKAWA support team.
The stable version is planned to be offered as a Tkool license.

**Comment by krmbn0576** [comment]
[1]
Under MIT License, you can use, publish, distribute and sublicense softwares.
So in this case OK.

**Comment by strcter** [comment]
Hi, Thanks for quick reply.
I will write the text in English here. (Tkool License was written in japanese, so I reported issue in japanese on GitHub)
Should I translate previous quesions? Are there available English version of Tkool License? 

[1] I understand, It's ok.

[2]
(1)
If it isn't permitted,
when contributer modifiy and run the MIT Licensed corescript,
it is a violation for Tkool License on many cases.
Because modified corescript is own program(in japanese word:自作プログラム),
So IMHO, it shall be permitted.

(2), (3)
If case[2]-(1) is permitted, 
I think [2] (2),(3) is also permitted naturally.

(4)
I think this is a borderline case.
All of RPG Tkool Software had been proprietary licensed until yesterday.
So, If someone use and play Tkool Software or Tkool Game, the man agreed with Tkool License, 
we couldn't imagine a case of non-officialy Tkool Software.
But corescript of Tkool MV license was freed under the MIT License, 
So we can suppose possibility of  forked version(i.e. Non-official but it's permitted legally by copyright holders) of Tkool Software.
In such case, what is mean of a Game made by Tkool?,
The game was editted by Official Tkool Editor?, or the game has possibility to run on corescript(which includes derivied version of corescript)
License Agreements looks like to not suppose such cases.(In addition, these doen't suppose that releasesing codes under the MIT License anyway)

Finally, I really loves Tkool Games.
I used to make games by RPG Tkool 2000 on Windows when I were teenager.
Thanks for releasing source codes under free license!

**Comment by iyokan-nico** [comment]
This time license became MIT because tkool community and DWANGO who manages "RPG atsumaru" proposed to KADOKAWA.

Therefore, corescript license is tkool license and MIT's duel license.
In general, loose rules take precedence over hard licenses, but we are not in a position to judge it.

This is also common sense talk, but the contract is for protecting business. And OSS is for developers to enjoy development and contribute to the community.
Unless there is inevitability,I think that is not it necessary to strict boundary examples.

**Comment by ghost** [comment]
@strcter If you solve issue, please close it.
