### ISSUE TITLE
Fix Utils.isNwjs can't distinguish between nwjs and electron.

### ISSUE THREAD

**Issue by shitake2333** [rpgtkoolmv/corescript#80]
This code can not further distinguish between nwjs and electron.
```javascript
Utils.isNwjs = function() {
    return typeof require === 'function' && typeof process === 'object';
};
```
We can do more accurate judgments through `process.versions.nw`.
```javascript
Utils.isNwjs = function() {
    return typeof require === 'function' && typeof process === 'object' && process.versions.nw != void 0;
};
```

**Comment by krmbn0576** [comment]
Thanks, but *electron* is out of the range of this project.
I don't think it's necessary...

**Comment by ghost** [comment]
Electron is out of scope.
if you need, please solve it by plugin!!
