### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by Siderg** [rpgtkoolmv/corescript#81]
There is noticeable performance drop between stable 1.4.0 version and OSS
I have create new project with RMMV 1.4.0 PC version and start playtest. Test map contains only player and 1 event who does nothing, without any plugins. Performance was great stable 60 fps. After that i compile OSS project like instruction says with node.js. Then add OSS files to project, what i create earlier, with replacement. Playtest starts with no problem, but i noticed that performance is different then before. Now average fps is ~48, i wait some time and call menu few times, and average fps on map goes up to ~54. 
Is this normal for this stage of development?
Sorry if i create this topic in wrong place. I'm not familiar with github.

**Comment by ghost** [comment]
I'll investigate them.

**Comment by Siderg** [comment]
It's strange but after i remove grass autotile from map in editor, after start playtest i got 60 fps on map, but after i call menu and return to map fps goes from 60 to 51-54 and after few more menu calls got 60 fps back. In game menu i have 30-36 fps no matter what i do.
If you need any information from my side tell me.

**Comment by shitake2333** [comment]
There was a similar situation on my side (Mozilla / 5.0 (X11; Ubuntu; Linux x86_64; rv: 50.0) Gecko / 20100101 Firefox / 50.0)
Whether it is a map scene or menu scene, FPS will be reduced to 30 ~ 40, then back to normal, and then lower.
I changed to v1.1b, there is no such problem.

**Comment by NectherLouie** [comment]
Just giving my observations here as well. It might not be happening on the OSS only because I noticed it as well on the new update. The game drops to 45 for some reason from time to time. Standard map and 4 events with menu switching.

**Comment by ghost** [comment]
in 1.4.0 tilemap impl updated, it may causes performance difference.

**Comment by ghost** [comment]
1.2b updates pixi-tilemap. does anyone try it?

**Comment by Siderg** [comment]
I've test it, but now i can't say for sure. When i create this topic my video card was really old and bad. And i saw a difference really easy. For now i've bought new video card and performance is good now, even if i compare 1.4.0 to 1.1b.
But i've done some tests on other computers where was a little difference in performance(not that noticeable like on my PC) before and i can say with 1.2b performance now is pretty much the same as in 1.4.0. So i think problem is solved?

**Comment by ghost** [comment]
Okay, thank you for testing !
