### ISSUE TITLE
NPM package for the corescript

### ISSUE THREAD

**Issue by niokasgami** [rpgtkoolmv/corescript#89]
I do know this supposed to be used under the licenses of MV, 
but wouldn't be nice to have access to the NPM package of the MV corescript for add them as dependencies for some plugin projects? so peoples can install them easily (or avoid to having to like go fetch the files directly from the github each time).

But on another side you also just want to have it as a module and not a in the whole projects (e.g dev a plugin for it)

I hope this could be a good idea for it!

**Comment by krmbn0576** [comment]
Oh, I think many of the MV game creators are unfamiliar for npm packages and standard frontend development.
I'm afraid I'm unwilling... 😖

**Comment by ghost** [comment]
It's useful for frontend developers, but Its not suitable for Standard RPG Maker's user.
We'd better create install script than npm.

**Comment by shitake2333** [comment]
We can use the Steam Workshop as RMMV plugin center, It's more suitable than NPM. The existing plugin management is very unfriendly(Not just when runtime).

But in this case, it's not just for corescript development team.

**Comment by niokasgami** [comment]
Haha well this was simply for dev purpose but i understand you guys points!
