### ISSUE TITLE
[Mechanic] HP/MP rounding error with equipment

### ISSUE THREAD

**Issue by Mkneeshaw** [rpgtkoolmv/corescript#91]
Reproducible: Yes
Impact: Low

When changing equipment, it is possible to lose/gain HP/MP due to the underlying data being stored as an integer instead of a float. RMMV recalculates the new stat value (after equipment change) to be as close to the previous percentage as possible, but then stores the new rounded value instead of the intended percentage. Because of this, undoing the most recent equip can cause the player to lose or gain HP/MP until either 1 HP or full HP is achieved (depending on the value change of the equipment and the starting values of the characters HP/MP).

> I'm afraid you addressed the very problem that plagues most RM users. Because it's stored as an integer and not a float, HP gets continuously lost. I'm afraid there's not a valid solution to it that prevents abuse of unequipping repetition other than reducing HP each time without rewriting the base structure of MV. Sorry I couldn't be of more help here.
-Yanfly

![67ad1f4e-255b-11e7-8358-c42a5268626d](https://cloud.githubusercontent.com/assets/16686828/25243665/d770ce5a-25cb-11e7-9dac-8d11479dd98e.png)

**Comment by krmbn0576** [comment]
>RMMV recalculates the new stat value (after equipment change) to be as close to the previous percentage as possible

I tried testing the same situation.
However, after changing the equipment, HP/MP were simply clamped between 0 and the max value.

I'm sorry but I don't know what situations you are concerned about. 😖

**Comment by niokasgami** [comment]
Did you tried without yanfly plugins?

**Comment by Mkneeshaw** [comment]
It has nothing to do with yanfly scripts. Its how the core script handles the data type. 

If we simply round the value before displaying it, we should be able to keep the float for calculations, but still display the value we would like to display. The bad part is that it doesn't look like RMMV differentiates between calling the HP for a calculation and calling it for a display value, so we would have to write a new method .paramUnrounded that returns the unrounded version whenever a calculation is to be done, and then allow it to use the original rounding for display calls or we could do the opposite. It really depends on if there are more calls for calculation or display.

**Comment by Mkneeshaw** [comment]
Clamp just keeps the HP value between 0 and Max which we obviously want to do. I assume it didn't round since most clamping functions don't. If a player has full health and unequips and then reequips they can lose or gain 1hp from the rounding error. I can show the problem in defualt/no plugin screenshots if it will help.

**Comment by Mkneeshaw** [comment]
/**
 * Returns a number whose value is limited to the given range.
 *
 * @method Number.prototype.clamp
 * @param {Number} min The lower boundary
 * @param {Number} max The upper boundary
 * @return {Number} A number in the range (min, max)
 */
Number.prototype.clamp = function(min, max) {
    return Math.min(Math.max(this, min), max);
};



Champ is not rounding

**Comment by niokasgami** [comment]
as I said stop assuming, 
before claiming a bug you should be able to reproduce it without any plugins or with a newer projects.
if they have plugins in it this not the responsability of the oss to find why it's bug with the said plugins.

as I said try to reproduce it with a fresh project without ANY plugins.
if it's doesn't bug without plugins, then it's a plugin bug. if you can reproduce without the plugins the said bug. then OSS will fix it.

**Comment by Mkneeshaw** [comment]
You are correct. I'll be more careful claiming a bug in the future. Thanks for checking into it.

The problem still exists in the original game, but equipping/unequipping hp items simply doesn't attempt to keep the same %. I had realized the original scripts use the same hprate function that Yanfly uses, but failed to realize you never use it for equipping. You only use it for 2 purposes: 1. confitional branch (is actor hp between x/y) and 2. to confirm if the actor is alive for combat conditions. I can't think of a possible issue with rounding in those two instances where we would need a float over an int.
